#!/usr/bin/env sh
set -ex

echo "Build hook running"

TAG=$1

export DESC="Lightweight php 7.2 container based on alpine with Composer installed and swoole ${TAG} installed."

export COMMIT_HASH=`git rev-parse --short HEAD`

export IMAGE_COMMIT=greenny/php72-swoole:${TAG}-${COMMIT_HASH}

export IMAGE_NAME=greenny/php72-swoole:${TAG}

export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`

echo "Image name: ${IMAGE_NAME}"
echo "Swoole version: ${TAG}"
echo "Docker description: ${DESC}"
echo "Docker commit hash: ${COMMIT_HASH}"
echo "Build date: ${BUILD_DATE}"

docker build --no-cache \
    --file Dockerfile \
    --build-arg BUILD_DATE=${BUILD_DATE} \
    --build-arg VCS_REF=${COMMIT_HASH} \
    --build-arg IMAGE_NAME=${IMAGE_NAME} \
    --build-arg SWOOLE_TAG=${TAG} \
    --build-arg DESC="${DESC}" \
    --squash --force-rm --compress --rm \
    -t ${IMAGE_NAME} .
